### ISSUE TITLE
Issue with payment dates for SwapFloatLeg

### ISSUE THREAD

**Issue by stanlxr** [domokane/FinancePy#106]
Hi, I have noticed the following payment date inconsistency between SwapFloatLeg and SwapFixedleg. With the same date generating convention, I get different payment dates for the float leg and fixed leg. 

**Below is the sample code to run:** 

from financepy.products.rates import *
from financepy.utils.date import *
import datetime

date = from_datetime(datetime.date(2021, 9, 1))

fixedleg_2 = SwapFixedLeg(effective_date=date, end_date='3y',
                          leg_type=SwapTypes.PAY, freq_type=FrequencyTypes.SEMI_ANNUAL,
                          day_count_type=DayCountTypes.THIRTY_E_360, calendar_type=CalendarTypes.UNITED_STATES,
                          coupon=0)

floatleg_2 = SwapFloatLeg(effective_date=date, end_date='3y',
                          leg_type=SwapTypes.PAY, freq_type=FrequencyTypes.SEMI_ANNUAL,
                          day_count_type=DayCountTypes.THIRTY_E_360, calendar_type=CalendarTypes.UNITED_STATES,
                          spread=0)

fixedleg_2.generate_payments()
floatleg_2.generate_payment_dates()

print("leg_2")
fixedleg_2.print_payments()
print("fleg_2")
floatleg_2.print_payments()

**Below is the output:**
leg_2
START DATE: 01-SEP-2021
MATURITY DATE: 03-SEP-2024
COUPON (%): 0
FREQUENCY: FrequencyTypes.SEMI_ANNUAL
DAY COUNT: DayCountTypes.THIRTY_E_360
PAY_DATE     ACCR_START   ACCR_END      DAYS  YEARFRAC    RATE      PAYMENT 
01-MAR-2022  01-SEP-2021  01-MAR-2022   180  0.500000  0.000000         0.00
01-SEP-2022  01-MAR-2022  01-SEP-2022   180  0.500000  0.000000         0.00
01-MAR-2023  01-SEP-2022  01-MAR-2023   180  0.500000  0.000000         0.00
01-SEP-2023  01-MAR-2023  01-SEP-2023   180  0.500000  0.000000         0.00
01-MAR-2024  01-SEP-2023  01-MAR-2024   180  0.500000  0.000000         0.00
03-SEP-2024  01-MAR-2024  03-SEP-2024   182  0.505556  0.000000         0.00

fleg_2
START DATE: 01-SEP-2021
MATURITY DATE: 03-SEP-2024
SPREAD (bp): 0
FREQUENCY: FrequencyTypes.SEMI_ANNUAL
DAY COUNT: DayCountTypes.THIRTY_E_360
PAY_DATE     ACCR_START   ACCR_END      DAYS  YEARFRAC
03-SEP-2021  01-SEP-2021  03-SEP-2021     2  0.005556  
03-MAR-2022  03-SEP-2021  03-MAR-2022   180  0.500000  
06-SEP-2022  03-MAR-2022  06-SEP-2022   183  0.508333  
03-MAR-2023  06-SEP-2022  03-MAR-2023   177  0.491667  
05-SEP-2023  03-MAR-2023  05-SEP-2023   182  0.505556  
04-MAR-2024  05-SEP-2023  04-MAR-2024   179  0.497222  
03-SEP-2024  04-MAR-2024  03-SEP-2024   179  0.497222 

**Issue**
Notice that 01/02-SEP-2024 is not a business day, the maturity date becomes 03-SEP-2024. But this should not affect previous dates in SwapFLoatLeg, i.e. the 01-SEP should have been preserved just as it is the case in SwapFixedLeg. 

I looked into the code, potential cause could be this part of code in the SwapFloatLeg file: 

scheduleDates = Schedule(self._effective_date,
                                 self._termination_date,
                                 self._freq_type,
                                 self._calendar_type,
                                 self._bus_day_adjust_type,
                                 self._date_gen_rule_type)._generate()

When Schedule is initiated, it already runs the function self._generate() once. Here the scheduled dates are obtained by running this function again, which in the case will give the scheduler a modified termination date (i.e. 03-SEP-2024 instead of the original 01-SEP-2024). I suppose the function to obtain the dates should be self.schedule_dates() ? 

Could you take a look at this when you have time? Thanks in advance!

**Comment by domokane** [comment]
I am looking at this now. Will let you know.

**Comment by domokane** [comment]
I have fixed this. I will release a new version to pip later.
