### ISSUE TITLE
Date issue w.r.t. Feb

### ISSUE THREAD

**Issue by stanlxr** [domokane/FinancePy#109]
Hi, I've noticed a potential issue with the add_tenor() function within the Date the object:

Let's say ref_date = 2021-09-29, I would expect the ref_date.add_tenor("6m") to return 2022-03-29 instead of 2022-03-28. I looked into the code, apparently the algo checks in every loop if the current day is larger than the month-end date. It adjusts it to the month-end date if true. The issue is that it will start to preserve the 28th once it passes Feb-2022, but I think it should always preserve the 29th, which is what I have provided as a reference. Otherwise this will cause problems with swap curve calibration due to grids not being aligned. 

Could you take a look at this at your earliest convenience? Thanks!

Sample code to run
```
from_datetime(datetime.date(2021, 9, 30)).add_tenor("6m")
Out[7]: 28-MAR-2022
```

**Comment by domokane** [comment]
OK. Let me look.

**Comment by domokane** [comment]
Fixed - releasing soon.
