### ISSUE TITLE
pv01 issue in OIS swaps

### ISSUE THREAD

**Issue by stanlxr** [domokane/FinancePy#110]
Hi, I noticed that there's a potential issue with the pv01 function in OIS swaps:

```
def pv01(self, valuation_date, discount_curve):
        """ Calculate the value of 1 basis point coupon on the fixed leg. """

        pv = self._fixed_leg.value(valuation_date, discount_curve)
        
        # Needs to be positive even if it is a payer leg
        pv = np.abs(pv)
        pv01 = pv / self._fixed_leg._coupon / self._fixed_leg._notional
        return 
```

Here you flipped the pv if its a payer (which results in neg pvs), but if the coupon rate is negative, I guess this won't work cause the pv01 will become negative. Can you take a look at this as well when you have time? Thanks!

**Comment by domokane** [comment]
Fixed. Releasing soon.
