### ISSUE TITLE
Issue with the swap rate function in OIS swaps

### ISSUE THREAD

**Issue by stanlxr** [domokane/FinancePy#111]
Hi, I've noticed a potential issue with the swap rate function in OIS swaps in addition to the one flagged before. 

```
    def swap_rate(self, valuation_date, oisCurve):
        """ Calculate the fixed leg coupon that makes the swap worth zero.
        If the valuation date is before the swap payments start then this
        is the forward swap rate as it starts in the future. The swap rate
        is then a forward swap rate and so we use a forward discount
        factor. If the swap fixed leg has begun then we have a spot
        starting swap. """

        pv01 = self.pv01(valuation_date, oisCurve)

        if valuation_date < self._effective_date:
            df0 = oisCurve.df(self._effective_date)
        else:
            df0 = oisCurve.df(valuation_date)

        floatLegPV = 0.0

        dfT = oisCurve.df(self._maturity_date)
        floatLegPV = (df0 - dfT) 
# Removed the next line as it seems unneccesary
#        floatLegPV /= self._fixed_leg._notional
        cpn = floatLegPV / pv01           
        return cpn
```

I understand that this is a quick-and-dirty way to get the floating leg PV. But if the day count convention of the swap is different than the underlying OIS discount curve, the above formula might not hold. I guess looping over the payments seems unavoidable in this case. 

Below is a quick demo using BBG to price a SONIA swap (market convention is ACT/365F) 
![image](https://user-images.githubusercontent.com/89845011/134806765-5ebf2c9a-ccb2-48a9-b0c2-690192a75dd5.png)
Noted that the floating leg has a pv of 0 as expected. But if I switch to ACT/360, the pv changes (equivalent to roughly 1 bps in forward rates space)
![image](https://user-images.githubusercontent.com/89845011/134806865-f5c1da41-6628-4679-8bcd-ba206a06fe26.png)
Could you please take a look at this? Many thanks

**Comment by domokane** [comment]
I have made changes and checked them in. I am having some numba issues but the rates stuff should work. Please take a look.
