### ISSUE TITLE
Add Github action to ensure Code Styling

### ISSUE THREAD

**Issue by VFermat** [domokane/FinancePy#115]
**What is this issue about**

To ensure coding styling (from what I saw, the repository is using PEP8), we should add a GitHub action that makes sure all code is compliant with PEP8

**Proposed solution**

Install autopep8 and an action to run the linter on the repository!

Related to #91

**Comment by domokane** [comment]
If you want to do that then please go ahead and I will pull it. I am not sure making it all pep8 compliant will be easy but it would be good to know which bits are not compliant.
