### ISSUE TITLE
Issue in OIS swap rate function

### ISSUE THREAD

**Issue by stanlxr** [domokane/FinancePy#118]
In the OIS swap rate function, you have changed from a discount factor difference representation to actually looping over the individual payments to calculate the OIS swap rate. In the former case, the notional is implied to be 1 so I requested that we remove the division of notional in calculating the par rate, however, as we have changed to the latter (which accommodates all swap conventions), the division of notional should be in place. 

"""
    def pv01(self, valuation_date, discount_curve):
        """ Calculate the value of 1 basis point coupon on the fixed leg. """

        pv = self._fixed_leg.value(valuation_date, discount_curve)        
        pv01 = pv / self._fixed_leg._coupon / self._fixed_leg._notional

        # Needs to be positive even if it is a payer leg and/or coupon < 0
        pv01 = np.abs(pv01)
        return pv01

##########################################################################

    def swap_rate(self, valuation_date, ois_curve, first_fixing_rate = None):
        """ Calculate the fixed leg coupon that makes the swap worth zero.
        If the valuation date is before the swap payments start then this
        is the forward swap rate as it starts in the future. The swap rate
        is then a forward swap rate and so we use a forward discount
        factor. If the swap fixed leg has begun then we have a spot
        starting swap. """

        pv01 = self.pv01(valuation_date, ois_curve)

        float_leg_value = self._float_leg.value(valuation_date,
                                             ois_curve,
                                             ois_curve,
                                             first_fixing_rate)
        
        cpn = float_leg_value / pv01           # need to divide the RHS by notional
        return cpn
"""

Could you take a look at this issue, many thanks!

**Comment by domokane** [comment]
I fixed this. I don't have time to roll a new release right now but you can download and install.
