### ISSUE TITLE
Issue with the date object

### ISSUE THREAD

**Issue by stanlxr** [domokane/FinancePy#135]
Hi I have noticed an issue with the financepy date object regarding the add_weekdays() function. Below is an example:

```
import datetime
from financepy.utils import from_datetime

today = datetime.date(2022,2,13)
next_weekday = from_datetime(today).add_weekdays(1).datetime()
last_weekday = from_datetime(today).add_weekdays(-1).datetime()
print("Today = {}, next weekday is = {}, last weekday is {}".format(today, next_weekday, last_weekday))
```
The result is: Today = 2022-02-13, next weekday is = 2022-02-16, last weekday is 2022-02-12, while I am expecting that next weekday is 2022-02-14 (Monday), last weekday is 2022-02-11 (Friday) because 2022-02-13 is a Sunday. Could you please take a look? Many thanks!

**Comment by domokane** [comment]
This has been fixed. Did not work when starting on a weekend. I have pushed the change. If you need a new release let me know.
