### ISSUE TITLE
(fx_vol_surface_plus) issue with strike interpolation

### ISSUE THREAD

**Issue by leogeogh** [domokane/FinancePy#136]
In the method delta_to_strike() of the class FxVolSurfacePlus the strike interpolation 

K = ((texp-t0) * K1 + (t1-texp) * K0) / (K1 - K0) returns negative values in some examples.

If a linear interpolation were performed the result would be instead:

K = (texp - t0) / (t1 - t0) * (K1 - K0) + K0

**Comment by domokane** [comment]
Let me look into this.

**Comment by domokane** [comment]
Hi - I have fixed it and pushed a new version of financepy to PYPI.
