### ISSUE TITLE
"bond.full_price_from_ytm"  is always computed by "face=100" right?

### ISSUE THREAD

**Issue by lan-slot** [domokane/FinancePy#149]
Dear author:

In "FINBOND_ExampleAppleCorp.ipynb", no matter what number is set to the face, for example what u set is "face = ONE_MILLION", the "bond.full_price_from_ytm(settlement_date, ytm, yieldConvention))"  is always computed by "face=100" right? Cause,If I change "face = ONE_MILLION" to any value, the result will not change. It is always "Full Price = = 102.091564"

**Comment by domokane** [comment]
Yes. The face_amount is only used to calculate the accrued interest and the principal (clean_price x face_amount).

All prices are on a face of 100.

**Comment by lan-slot** [comment]
> Yes. The face_amount is only used to calculate the accrued interest and the principal (clean_price x face_amount).
> 
> All prices are on a face of 100.

thank u so much!
