### ISSUE TITLE
Accrued interest on coupon payment day

### ISSUE THREAD

**Issue by DominicHong** [domokane/FinancePy#155]
Hi Professor,
Bond and BondZero's calc_accrued_interest() shows that: 
``` Python 
# coupons paid on a settlement date are paid
            if self._coupon_dates[iFlow] >= settlement_date:
```
This equal sign means the whole coupon would be paid as ACCRUED INTEREST to the seller on settlement day(if it's the same as coupon payment day), while the seller would still receive coupon payment from bond issuer. 
This makes no sense. In real trade market, the ACCRUED INTEREST on coupon payment day is 0. 
What's your opinion? 

``` Python
    def calc_accrued_interest(self,
                              settlement_date: Date,
                              num_ex_dividend_days: int = 0,
                              calendar_type: CalendarTypes = CalendarTypes.WEEKEND):

        .....

        for iFlow in range(1, num_flows):
            # coupons paid on a settlement date are paid
            if self._coupon_dates[iFlow] >= settlement_date:
                self._pcd = self._coupon_dates[iFlow - 1]
                self._ncd = self._coupon_dates[iFlow]
                break
```

**Comment by domokane** [comment]
Hi Dominic - you are right. This looks wrong. However if we change this then we need to make sure that the coupon schedule means that there is a full coupon payment on the settlement date if the coupon is on a settlement date. Can you check ?

**Comment by DominicHong** [comment]
@domokane 'make sure there is a full coupon payment on the settlement date if the coupon is on a settlement date' 
What do you mean?
I checked the code. The coupon payment dates and cashflow should be correct. 
Anything else I missed out?
