### ISSUE TITLE
Add Equity Swap Product

### ISSUE THREAD

**Issue by nashquant** [domokane/FinancePy#159]
Hi all, 

I'm planning to work towards including Equity Swaps as a product type. 
Let me know if this conflicts with anyone's work : )

Summary (from Hull's Options, Futures and Other Derivatives):
In an equity swap, one party promises to pay the return on an equity index on a
notional principal, while the other promises to pay a fixed or floating return on a
notional principal. Equity swaps enable a fund managers to increase or reduce their
exposure to an index without buying and selling stock. An equity swap is a convenient
way of packaging a series of forward contracts on an index to meet the needs of the
market.

References:
John Hull - Options, Futures and Other Derivatives(9th Edition)/
John Hull Technical Notes on Equity Swaps - http://www-2.rotman.utoronto.ca/~hull/technicalnotes/TechnicalNote19.pdf

Best,
Matheus

**Comment by domokane** [comment]
Sounds good. Go for it. You might want to copy something like the FRA pricer in rates. 
Best
D

**Comment by nashquant** [comment]
Hi Dominic, 

Thank you for the advice! Made some progress yesterday on that, will keep you posted.

**Comment by nashquant** [comment]
Hey @domokane,

Thanks for checking this out. Still pending is to Rename class SwapEquityLeg class to EquitySwapLeg. 
In addition to that, I'm thinking that print_payments and print_valuation now is different between FixedLeg and FloatLeg, can I work to standardize this?

Thank you!
Matheus
