### ISSUE TITLE
Refactor barrier option code to extract core model code from products into model folder.

### ISSUE THREAD

**Issue by domokane** [domokane/FinancePy#161]
Some of the product classes in the equity products (and other product) folder contain core model quant code. For example the Equity BarrierOptions class. The core code should be moved into models so that the product classes contain just an interface.

**Comment by domokane** [comment]
Hi Gautier
This is new - I posted it last week so it's yours if you want it. 
Yes that would be correct. I think a number of other models have the same issue but I would like to start with barrier options.
Best
D

**Comment by domokane** [comment]
Create a new model file under the models folder and put the core code there. The interface should only take floats and integers and bools and types and rates.

**Comment by gpelleri** [comment]
Both _value_one and value_mc uses severals class attributes (expiry, strike ...) : do you want to pass the EquityBarrierOption to be passed as a parameter & create getters for each attributes needed or rather pass each needed attributes as a parameter ? 
As far as I've seen, others models avoid being class specific, do you confirm i should keep the same logic here ?

**Comment by domokane** [comment]
Hi - no I want the interface to the models to be as simple as possible so that they can be called directly if needed without using the higher level classes. This is sometime required for speed.

**Comment by domokane** [comment]
I see the product classes as wrappers around the lower level models.

**Comment by parthvnp** [comment]
@gpelleri  Any updates on the issue? If you need help, more than happy to collaborate!

**Comment by gpelleri** [comment]
Hi @parthvnp , i have already done a PR a few weeks ago which was merged. I was wondering if the Date needed to be passed as floats but as sir @domokane merged and refactored without modifying the Dte format i'm unsure wheter this is still needed or not.

**Comment by domokane** [comment]
Hi - it would be good if one of you could remove the dates from the model interface as it is against the design I would like to enforce - I want the underlying models to be directly callable from outside the product in case that becomes necessary. Then I can close this issue.

**Comment by gpelleri** [comment]
Sure, my bad for the misunderstanding then. I'll do it today

**Comment by domokane** [comment]
OK thanks.
