### ISSUE TITLE
Re-generate manual when master is updated

### ISSUE THREAD

**Issue by FergalOK** [domokane/FinancePy#181]
To prevent the manual from being out of date, it should be updated when master is changed.

An example of how pandas keeps their documentation up to date: https://github.com/pandas-dev/pandas/blob/main/.github/workflows/docbuild-and-upload.yml

We would want to do this, but to update [FinancePyManual.pdf](https://github.com/domokane/FinancePy/blob/master/docs/FinancePyManual.pdf) (instead of uploading to a website).

One way of doing this would be similar to [this stackoverflow post](https://stackoverflow.com/questions/73806448/can-github-actions-edit-parts-of-readme-md)

**Comment by domokane** [comment]
Thanks. But I just realised I need latex for it to work! Oops.

**Comment by FergalOK** [comment]
What difference would that make?

**Comment by domokane** [comment]
Can you install Miktex on GitHub servers ?

**Comment by FergalOK** [comment]
I don't see why not, you can run `apt install` just fine.

I've been struggling to actually get the script to work on my own computer though.

**Comment by domokane** [comment]
There were some issues that I fixed yesterday. Some of the new pushes by others included characters that were problematic such as "##" and "&" and urls. I removed these and pushed. It should work now.
