### ISSUE TITLE
Date Schedule._generate issue

### ISSUE THREAD

**Issue by gbarbe77** [domokane/FinancePy#185]
Hi,

There is an issue on Schedule._generate with the following specs:
            
OIS(
        effective_date=Date(28, 4, 2023),
        termination_date_or_tenor=Date(30, 4, 2024),
        fixed_leg_type=SwapTypes.PAY,
        fixed_coupon=spot_rate / 100,
        fixed_freq_type=FrequencyTypes.ANNUAL,
        fixed_day_count_type=DayCountTypes.ACT_360,
        float_freq_type=FrequencyTypes.ANNUAL,
        float_day_count_type=DayCountTypes.ACT_360,
        calendar_type=CalendarTypes.UNITED_STATES,
        bus_day_adjust_type=BusDayAdjustTypes.MODIFIED_FOLLOWING,
        date_gen_rule_type=DateGenRuleTypes.BACKWARD
        )

I get the following error:
FinError("Two matching dates in schedule")

I raise to you because of the title of the section. This is something that normally should not happen per the title.

      #######################################################################
        # Check the resulting schedule to ensure that no two dates are the
        # same and that they are monotonic - this should never happen but ...
        #######################################################################

Thank you :)

**Comment by domokane** [comment]
OK. Will take a look. Thanks.

**Comment by domokane** [comment]
I have pushed a bug fix. Please take a look.
