### ISSUE TITLE
Bond Curve Fitting

### ISSUE THREAD

**Issue by gulls-on-parade** [domokane/FinancePy#190]
Is there functionality and/or an example available to fit a discount curve to actual bond market prices - in the presence of overlapping issues/CUSIPs? 

Akin to the [FittedBondCurve object in QuantLib](https://quantlib-python-docs.readthedocs.io/en/latest/termstructures/yield.html#fittedbondcurve)

It looks like the BondYieldCurve object achieves this in YTM space (but notes should not be used for pricing), whereas the BondZeroCurve performs traditional bootstrapping and therefore has a monotonicity requirement. I suppose creating a BondZeroCurve from a BondYieldCurve is possible, if one were to pick specific tenors  - but perhaps that's not quite the same as fitting discount curve in price space straight away?

**Comment by domokane** [comment]
Hi - I missed this. I will get back to you asap.
Best
D
