### ISSUE TITLE
CDSOption insensitive to vol for Receiver

### ISSUE THREAD

**Issue by HZS2** [domokane/FinancePy#193]
Works for Payer option. If the direction of Protection is Short, as below per instruction, the option price does not change ?
cdsOption=CDSOption(expiry_date, maturity_date, strike, notional, False)
cdsOption.value (valuation_date, issuer_curve, vol)

**Comment by domokane** [comment]
OK. I will look as soon as I get time after hols.
Best
D

**Comment by domokane** [comment]
Hi - I have added a short protection example to the test file

https://github.com/domokane/FinancePy/blob/master/tests_golden/TestFinCDSOption.py

and it seems to work correctly. Send me your code if you still have a problem after checking against this test. 

It could be that the option is far OTM or ITM. 

Best
D

**Comment by HZS2** [comment]
Dear Professor O'Kane,

Thank you for testing and the reply. ITM is a bit confusing, so I will
continue to test it out.

I wonder if there is a way to modify CDSIndexOption to accommodate CDX.HY
swaptions?  As I was trying to convert all price based options into running
spread one, but for some unknown reasons I am not converging with CDSO
(attached IMG file) .. would you be so kind to have a look?  Sorry for
taking your valuable time on this matter.
********************************************************************************
indexMaturityDates=[Date(20,6,2026),Date(20,6,2028),Date(20,6,2030),Date(20,6,2033)]
valuation_date, expiry_date, maturity_date =
Date(30,6,2023),Date(20,9,2023),Date(20,6,2028)
S=429/10000  #par spread converted from price 102.69%
#libor_curve using 5% flat
index_coupon=500/10000
indexRecovery = 0.3
vol=0.36 # from CDSO
cds_contracts=[]
for dt in indexMaturityDates:
    cds=CDS(valuation_date, dt, S)
    cds_contracts.append(cds)

index_curve=CDSCurve(valuation_date, cds_contracts, libor_curve,
indexRecovery)

fwdSpread=CDS(valuation_date, maturity_date, S).par_spread(expiry_date,
index_curve, indexRecovery)
fwdDuration=CDS(valuation_date, maturity_date, S).credit_dv01(expiry_date,
index_curve, indexRecovery)
#strike price 100.5%, UF=-0.5%
strike = index_coupon-0.5%/fwdDuration/10000
option=CDSIndexOption(expiry_date, maturity_date, index_coupon, strike,
notional)
v_pay, v_rec=option.value_adjusted_black(valuation_date, index_curve,
indexRecovery, libor_curve, vol)
#0.139%, 3.54% vs. Bloomberg 0.73%, 1.885%
********************************************************************************

Sincerely,
Hong Sherwin

**Comment by HZS2** [comment]
sorry... re-attaching CDSO to match a/m inputs.
