### ISSUE TITLE
Bond OAS and accrued interest

### ISSUE THREAD

**Issue by gulls-on-parade** [domokane/FinancePy#196]
@domokane It looks like the latest version of bond.option_adjusted_spread() incorrectly incorporates accrued interest (multiplying by par, when that is already internalized in the accrued interest function). Beyond this, though, it seems like something else might be amiss with the OAS-related formulas (bond.option_adjusted_spread() and bond.dirty_price_from_oas().

Thanks

**Comment by domokane** [comment]
Let me check this asap. This should have been caught by my tests. Apols if not.
Best
D

________________________________
From: gulls-on-parade ***@***.***>
Sent: 25 August 2023 10:04 PM
To: domokane/FinancePy ***@***.***>
Cc: domokane ***@***.***>; Mention ***@***.***>
Subject: [domokane/FinancePy] Bond OAS and accrued interest (Issue #196)


@domokane<https://github.com/domokane> It looks like the latest version of bond.option_adjusted_spread() incorrectly incorporates accrued interest (multiplying by par, when that is already internalized in the accrued interest function). Beyond this, though, it seems like something else might be amiss with the OAS-related formulas (bond.option_adjusted_spread() and bond.dirty_price_from_oas().

Thanks

**Comment by domokane** [comment]
I have just pushed V0.32 which fixes the bug - I had scaled the accrued by par twice so it was 100 times too big !
