### ISSUE TITLE
Backtesting of Strategy

### ISSUE THREAD

**Issue by Akshat111111** [domokane/FinancePy#204]
Is there any new feature for backtesting our strategy this FinancePy provides??

**Comment by domokane** [comment]
Not currently. It might be added in the future.

**Comment by Akshat111111** [comment]
Should I work on it, I think integrating backtrader at the beginning will be helpful?? Sir What you think about it ??

**Comment by domokane** [comment]
Can you specify exactkly what it would involve. I am not sure it should be part of FinancePy. But maybe FinancePy should be amended or extended to make it possible for it to be used by something else.

**Comment by Akshat111111** [comment]
Yeah, I am considering the extension of it with various parameters.
