### ISSUE TITLE
'bond.print_payments' error 

### ISSUE THREAD

**Issue by JasonG78** [domokane/FinancePy#205]
When running the FINBOND_ExampleAppleCorp notebook, I receive the following error:  

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[33], line 1
----> 1 bond.print_payments(settle_dt)

AttributeError: 'Bond' object has no attribute 'print_payments'

**Comment by domokane** [comment]
Thanks. I will fix this asap.

**Comment by domokane** [comment]
I have released a new version 0.34. It should work.
