### ISSUE TITLE
 Name 'swap_types' is not defined

### ISSUE THREAD

**Issue by gaoming714** [domokane/FinancePy#211]
I've just started using FinancePy and I'm using examples
for example FINIBORSWAPTION_ComparisonWithQLExample.ipynb

when it comes to this variable **swap_types.PAY**  it says it is not defined.

I looked at the file and it seems like it's not defined anywhere. 
Maybe I think I've made some basic mistakes.

**Comment by domokane** [comment]
Hi - it should be SwapTypes. I will fix this and push correct notebooks tomorrow.
Best
D

**Comment by gaoming714** [comment]
So fast repair. Let's IMPROVING THE LIBRARY.
(fixed on commit b23fd84)

**Comment by domokane** [comment]
A new version 0.360 has been released. The notebooks should all work now.
