### ISSUE TITLE
How to deal with same maturity bonds for bootstrap curve? 

### ISSUE THREAD

**Issue by jingmouren** [domokane/FinancePy#213]
I find that the bond pool have different bond with same maturity date.
For calculate YTM, I can use the mean of YTM of those same maturity date bonds.
But for bootstrap zero rate, the bootstram example notebook use clean price. And the underline code have monotonicity check.
I think use the mean of clean price is not the correct usage. So how to deal with that case?

Besides. what's the progess of #190 creating a BondZeroCurve from a BondYieldCurve?

**Comment by domokane** [comment]
Hi - I will look this weekend and get back to you.
D

**Comment by domokane** [comment]
I don't see how you can fit two bonds with same maturity but different prices to the same curve. It's ambiguous. You need to choose one of the bonds.
