### ISSUE TITLE
Bond() does not have a "face amount" input

### ISSUE THREAD

**Issue by priyanf** [domokane/FinancePy#216]
Although in the PDF manual it states: 

**Bond**
Create Bond object by providing the issue date, maturity Date, coupon frequency, annualised coupon, the
accrual convention type, **face amount** and the number of ex-dividend days. A calendar type is used to
determine holidays from which coupon dts might be shifted. 

There appears to be no "face amount" input in the function.

**Comment by domokane** [comment]
Manual has been updated.
