### ISSUE TITLE
Getting an error when running the Key Rate Duration method:

### ISSUE THREAD

**Issue by priyanf** [domokane/FinancePy#217]
Getting an error when running the Key Rate Duration method: 

  File ~\anaconda3\Lib\site-packages\financepy\products\bonds\bond_zero_curve.py:90 in _bootstrap_zero_rates
    optimize.newton(_f, x0=df, fprime=None, args=argtuple,

  File ~\anaconda3\Lib\site-packages\scipy\optimize\_zeros_py.py:381 in newton
    raise RuntimeError(msg)

**RuntimeError: Failed to converge after 100 iterations, value is nan.**

Example to replicate:
OBJECT TYPE: Bond
ISSUE DATE: 15-JAN-2022
MATURITY DATE: 15-JAN-2025
COUPON (%): 22.5
FREQUENCY: FrequencyTypes.SEMI_ANNUAL
DAY COUNT TYPE: DayCountTypes.ACT_ACT_ICMA
EX_DIV DAYS: 0

settle_dt = Date(30, 7, 2024) 
bond_current_date_ytm =  0.1005

This then gives the error above:
key_rate_dur = bond_1.key_rate_durations(settle_dt, bond_current_date_ytm)

_Originally posted by @priyanf in https://github.com/domokane/FinancePy/issues/182#issuecomment-2316682095_

**Comment by domokane** [comment]
I fixed this and pushed. Will be in next release.
