### ISSUE TITLE
Bond Key Rate Duration Calculator

### ISSUE THREAD

**Issue by domokane** [domokane/FinancePy#33]

**Comment by badalsarkar** [comment]
Hello @domokane ,
I would like to work on this issue. Please let me know if it is alright.
Thanks you.

**Comment by domokane** [comment]
Sure. Take a look at the code. We can discuss how to do it. If possible, I suggest putting as much of the code logic under models rather than putting it under FinBond.

It can then be called from the FinBond class.

I have not checked this but you may want to use this as a test case.

https://blog.deriscope.com/index.php/en/excel-quantlib-key-rate-duration

If you stop or change your mind, let me know.

Regards
D

**Comment by badalsarkar** [comment]
Thank you. I am looking at the code base. And once I have a plan, I will discuss with you.

**Comment by sagayev** [comment]
Dear @domokane I have done some calculations. I will send you a notebook for your review.  If I am on the right track I can incorporate into code together with the test cases.

**Comment by sagayev** [comment]
I am attaching the notebook here. Someone else may have an opinion or suggestion.

[KRD_draft_by_sagayev.zip](https://github.com/domokane/FinancePy/files/10802694/KRD_draft_by_sagayev.zip)

.ipynb file inside a zipped file.

**Comment by domokane** [comment]
Hi - this looks pretty good. The differences are probably due to small details in the price-yield formula. Maybe try implementing it as a function. Please think about where it should go - should it be part of a separate key rate class ?
