### ISSUE TITLE
BBG Testing Examples

### ISSUE THREAD

**Issue by domokane** [domokane/FinancePy#35]
If anyone has access to Bloomberg analytics that I can compare to then please send examples. 
Especially with regards to 
- Bonds - bullet, floating rate notes, perpetuals, step-ups, callable, puttable
- Convertibles - all sorts
- Options on bonds
- FRAs
- Interest rate futures
- Swaps 
- Cross currency swaps
- Swap curves construction
- OIS
- Caps, floors, swaptions
- Other exotics
etc...

**Comment by gulls-on-parade** [comment]
Still interested in these? Might be able to help

**Comment by domokane** [comment]
Please email me any examples and I will try to make a notebook as a test.  quant@financepy,com

**Comment by sagayev** [comment]
I have tested the US Treasury security against the **Bloomberg** screen on a notebook. The cashflow dates and accrued interest amounts do not match. I am attaching it here as PDF. Please let me know where I should adjust the code. If I can then I rewrite the code and submit a PR. 

[FinancePy_US_Treasury_check_with_Bloomberg_screen.pdf](https://github.com/domokane/FinancePy/files/10608737/FinancePy_US_Treasury_check_with_Bloomberg_screen.pdf)

**Comment by sagayev** [comment]
> I have tested the US Treasury security against the **Bloomberg** screen on a notebook. The cashflow dates and accrued interest amounts do not match. I am attaching it here as PDF. Please let me know where I should adjust the code. If I can then I rewrite the code and submit a PR.
> 
> [FinancePy_US_Treasury_check_with_Bloomberg_screen.pdf](https://github.com/domokane/FinancePy/files/10608737/FinancePy_US_Treasury_check_with_Bloomberg_screen.pdf)

Dear @domokane did you have a chance to look at the example above? It includes both BBG screen and the code. You can replicate it easily.

**Comment by domokane** [comment]
Hi Sagayev

I have fixed it and pushed a new version of financepy to PYPI. Here is an example notebook.

https://github.com/domokane/FinancePy/blob/master/notebooks/products/bonds/FINBOND_ExampleUSTreasury_CUSIP_91282CFX4.ipynb

Cheers
D
