### ISSUE TITLE
Bond model doesn't handle ex-div period for UK Gilts

### ISSUE THREAD

**Issue by jonfreedman** [domokane/FinancePy#36]
UK Gilts can have negative accrual, this applies for 6 business days prior to the coupon.

Other issuers have similar treatment e.g. Australian bonds have 7 calendar days of ex-div.

**Comment by domokane** [comment]
OK. I will look at this. It should be a straightforward fix. Do you have a numerical example say from BBG I can tie out to ?

**Comment by jonfreedman** [comment]
You should be able to get access to DMO closing prices which has dirty and clean prices, yield mod dur and int acc via https://www.dmo.gov.uk/data/treasury-bills/prices-and-yields/

**Comment by domokane** [comment]
I added ex-dividend dates to the FinBond class. When you calculate the accruedInterest it defaults to zero ex-div dates. But if you pass a non-zero number of days and a calendar it determines the ex-div date accordingly and then the accrued. There is a test in TestFinBond.py that ties out this example on page 16 of https://www.dmo.gov.uk/media/14702/pig201204.pdf . I find some sources like this give 7 BD for gilts and some that give 6 BD. I assume that 6 is now correct. This is something the user passes in. If you have a table of conventions then I can put them into the FinBondMarket DB.

**Comment by jonfreedman** [comment]
If you read the ex-div settings from Bloomberg static data (EX_DIV_DAYS & EX_DIV_CALENDAR fields), that may be a source of the confusion as those field values are sometimes wrong (e.g. AUD bonds saying they have 7 days ex-div with a Sydney calendar) or confusing (GBP bond saying it has 8 days ex-div (6 business days + sat + sun) which will then be updated if a holiday falls in the period).

GBP (6bd) and AUD (7cd) are the only G10 issuers I'm aware of with ex-div periods, but a lot of JP corp bonds use it as well.

**Comment by domokane** [comment]
I don't have access to Bloomberg static data. However the code can now handle these situations given the number of days and the correct calendar - NONE for calendar dates, WEEKEND for weekdays and a country name for business days in that country only.
