### ISSUE TITLE
Add an Equity Index Option product type

### ISSUE THREAD

**Issue by domokane** [domokane/FinancePy#54]
Add a product type for an option on an equity index called FinEquityIndexOption

This is similar to an Equity vanilla option but customised to index options. 

The option can be European or American exercise. 

The valuation can take in the futures price rather than the spot price.

It also needs an implied volatility calculation.

Most of this can be copied from FinEquityVanillaOption.

As we have index futures contracts, pricing uses Black's model rather than Black-Scholes.

You will need to add a test module and a notebook showing how this product works.

Reference

https://globaljournals.org/GJMBR_Volume12/10-Pricing-of-Index-Options-Using-Blacks-Model.pdf

**Comment by Sean-Koval** [comment]
Hey is this issue still open? I would love to take on the task.

**Comment by domokane** [comment]
You’re welcome to do it. Use FinEquityOption as a guide. Let me know if you have any questions.
Regards
D

**Comment by shunmaruko** [comment]
Hi @domokane,
It seems that FinEquityIndexOption class is not implemented yet.
If it is not completed,  I would like to take over the work.

Best regards,

**Comment by shunmaruko** [comment]
Hi @domokane, 

Thank you for your reply. I'm working on it.Just a quick question.
implied volatility needs to be calculated in case of American Index Option?
I'm glad if you would tell me what kind of algorithm is used in practice.

Best Regards,
