### ISSUE TITLE
solveforsmilestrike

### ISSUE THREAD

**Issue by mattdoub** [domokane/FinancePy#60]
Once I have a FxVolSurface object calibrated I am trying to retrieve the Strike corresponding to a set deltaTarget and ExpiryDate. This would be used to price a fxVanillaOption with specified delta as input instead of specified strike.

#Issue 1 
This function doesn't seem to exist in the class functions with only 2 args as parameters (self, deltaTarget as float,ExpiryDate as FinDate). 

#Issue 2 (alternative using solveForSmileStrike)
solveForSmileStrike seem to do the job but only for specific Expiry dates. However in FinFXVolSurfacePlus the function solveForSmileStrike takes into parameters:
OptionTypeValue
deltaTarget
tenorIndex
initialValue

This currently returns an error probably because the args (strikes = args[9] and gaps = args[10]) are not specified when calling deltaFit

**Comment by domokane** [comment]
Hi Matt
I have actually put this function - your issue 1 - on my to-do list - I discussed this with Saeed Amen last week. 
I can probably do this quite quickly. Regarding the error in #2, I will take a look later today and get back to you.
Regards
D

**Comment by domokane** [comment]
Matt - take a look at the latest version I just pushed. There are two new functions - 

volatilityFromDeltaDate
volatilityFromStrikeDate

The name says what they do. I have added an example to TestFinFXVolSurfacePlus

**Comment by mattdoub** [comment]
Looks good!

**Comment by mattdoub** [comment]
Hi Dominic - volatilityfromDeltaDate looks to be commented in the FinEquityVolSurface class. Any particular reason?

**Comment by domokane** [comment]
No. I just need to test it.

**Comment by domokane** [comment]
It needed work. I have fixed it now. Look at the test example in TestFinEquityVolSurface.
