### ISSUE TITLE
FinEquity...Options dividends input

### ISSUE THREAD

**Issue by mattdoub** [domokane/FinancePy#64]
Looking at Equity products. FinEquityVanillaOption methods for example take as argument for the dividend as a float. Would be nice to have the dividendCurve object passed as argument directly similar to the discountCurve instead of passing dividendCurve.df(self._expiryDate)

**Comment by domokane** [comment]
Agree. This is also on my to-do list. I can prioritise this. 

Also, is it common for equity derivative traders to extract dividends and rates from put-call parity arguments ?

Also, what's your interest / experience in this area ? Are you able to contribute as a developer ?

**Comment by mattdoub** [comment]
Ideally you have access to forwards directly. If you don't using the PUT-CALL parity will do the trick but the prices of the Calls and Puts as input need to be well contributed by market makers otherwise the quality of your forwards will be poor.
Finally, it is also common to have access to Vols quoted as Spot Moneyness (for example 3M 80%, where 80%  means 0.8*Spot_Price) and to have access to Vols quoted as Forward Moneyness (3M 80%, where 80% means 0.8*Forward_Price). It becomes quite easy to retrieve the forward price from the equivalent 2 vol Smiles (One quoted spot moneyness and the other quoted forward moneyness)

**Comment by domokane** [comment]
This is done. So I am closing this.

If you need a helper functions to extract the dividend from put-call prices let me know.
