### ISSUE TITLE
G10 Calendars

### ISSUE THREAD

**Issue by gulls-on-parade** [domokane/FinancePy#65]
@domokane , awesome work with this package! Great to see everything written in Python.

One feature request - it would be great to get calendars added for the rest of the G10 markets. Could use [QL calendars](https://www.quantlib.org/reference/group__calendars.html) as a reference.

Thanks!

**Comment by mwalkup55** [comment]
I would second this, perhaps could use QuantLib calendars to populate?

**Comment by domokane** [comment]
Hi - Reworking and extending FinCalendar is on my to-do list. I will look at completing G10 as soon as I can. Cheers D

**Comment by domokane** [comment]
I just added calendars for Germany, France, Canada, Switzerland, Italy and Sweden. If you have specific requests let me know. It does not take long if I have a gap. I am closing this for now. 

If you wish to get involved and add calendars yourself then please do so and send your code to me or do a pull request. D

**Comment by domokane** [comment]
Done. I can't promise to be as fast in future. ;-)

**Comment by gulls-on-parade** [comment]
I think latest commit introduced a small bug in FinCalendar.isBusinessDay():
`if dt.isWeekend():` became `if self._dt.isWeekend():`, however this method is sometimes called before `self._dt` is instantiated.

Cheers

**Comment by domokane** [comment]
Fixed.
