### ISSUE TITLE
Documentation in html

### ISSUE THREAD

**Issue by epogrebnyak** [domokane/FinancePy#71]
That for putting up and updating the package. Have you thought of html version of documentation, possibly with sphinx?

**Comment by domokane** [comment]
I don't really know sphinx. I initially liked the idea of a pdf file that I could customize so I built some code in docs to create that. If it's not too hard or if someone else wants to add it, I would include it.

**Comment by nhaga** [comment]
Jupyterbook mught be a good solution. You basically just build normal notebooks, create a TOC file and it will generate the HTML. Then, by setting up GitHub Actions, the output can be automatically published on each update

**Comment by epogrebnyak** [comment]
Just to note - Jupyterbook itself is built around sphinx, it uses sphinx to
build documentation with a special parser to process the notebooks.

вт, 23 февр. 2021 г., 12:02 David Duarte <notifications@github.com>:

**Comment by epogrebnyak** [comment]
> I don't really know sphinx. I initially liked the idea of a pdf file that I could customize so I built some code in docs to create that. If it's not too hard or if someone else wants to add it, I would include it.

The promise of sphinx is that you can generate both html documentation and the pdf file as it was usual in early days of python. 

I think adding html documentation is a great benefit for a user, but it may also expose more things that might need change or polishing.

Let me try to generate some sphinx docs for the package and put a link here to judge if they are useful.

**Comment by epogrebnyak** [comment]
Superseded by #83
