### ISSUE TITLE
V0.20 - Testing Framework

### ISSUE THREAD

**Issue by domokane** [domokane/FinancePy#81]
Please use this issue thread for all comments related to the current refactoring + pytest + docs

**Comment by domokane** [comment]
@epogrebnyak CI seems to have broken by the merge. Can you check. I am getting a problem renaming the file Frequency.py. It already was changed but I am using vscode which does not seem to see the change.

**Comment by epogrebnyak** [comment]
I do not see you merging #80 you just closed the pull request.

вс, 7 мар. 2021 г., 15:18 domokane <notifications@github.com>:

**Comment by domokane** [comment]
I did the following:

git checkout -b ru-corporate-master more_pep_8

git pull https://github.com/ru-corporate/FinancePy.git master

then I saw all your changes. All but 2 or 3 made changes that were incompatible with my renaming. I did not merge these changes. 

I then committed the changes and pushed out a new version.

**Comment by epogrebnyak** [comment]
Let me pull back back from your dev branch and restore the tests.

**Comment by domokane** [comment]
OK. If I am doing this incorrectly, let me know. 

Can you consider deleting all of the old TEST_  files  under the tests folder except for the ones that you have done - it is confusing as I don't want to maintain the "unused" tests in the tests folder except for the completed unit tests.

**Comment by epogrebnyak** [comment]
> OK. If I am doing this incorrectly, let me know. This is all quite new to me.

Branching is not the easiest topic, sometimes teams resort to "trunk-based" development where everyone commits directly to one development branch, with caution. 

I'm not a git guru either, but I think when you merge from the web interface, you get a mention of that in the PR, so easier to follow what happened. 

> Can you consider deleting all of the old TEST_ files under the tests folder except for the ones that you have done 

I was thinking keeping the old tests in tests folder and continually renaming them into `tests_something.py`, so it will be clear what parts of code still need testing. Can we leave the unused tests for a while in `tests` folder? They do not need to be maintained, they are for rewrite.

**Comment by epogrebnyak** [comment]
Try merging https://github.com/domokane/FinancePy/pull/84 - via web interface

**Comment by domokane** [comment]
The problem with leaving them there is that 
- They may get out of sync with the refactoring as I don't test them
- I might accidentally work on a test case in the tests folder confusing it with tests_golden
- It will confuse people
- It is much more *embarrassing* to see an almost empty unit tests folder ;-) and so its more an incentive to write the test cases.

**Comment by domokane** [comment]
BTW - the web interface told me to use the command line. If I could do it via the web interface I would.

**Comment by domokane** [comment]
Looks like the CI is running ok. Good !

**Comment by epogrebnyak** [comment]
>     * It is much more _embarrassing_ to see an almost empty unit tests folder ;-) and so its more of an incentive to write the test cases.

Perhaps you are right!  ) 

Made a PR  with few new commits https://github.com/domokane/FinancePy/pull/85 (git wants to merge more, but they are coming from your dev branch)

**Comment by epogrebnyak** [comment]
Can probably close this isuue? We have test frameworks in place, next is adding more tests.

**Comment by domokane** [comment]
Let me test it after I pull your changes. If it all works then I will close it.

**Comment by epogrebnyak** [comment]
Please also close orphan issues #39 and #40

**Comment by FergalOK** [comment]
The tests aren't running because of `forceobj=True` added in the last commit to `newton_secant` in `solver_1d.py` ([here](https://github.com/domokane/FinancePy/commit/2d43d10780dcb9afbcefee805c2660c26da08ab9#r57265052)).
I've finished porting over tests from tests_golden, but loads of them are failing after the last commit (2d43d10): [test output](https://github.com/FergalOK/FinancePy/runs/3733508103).
Should I assume that the new results are correct and change them to match?

**Comment by domokane** [comment]
Where can I see the messages and how much they are failing by ?
D x

**Comment by FergalOK** [comment]
I linked to the output: https://github.com/FergalOK/FinancePy/runs/3733508103

**Comment by domokane** [comment]
I changed the date generation so many things will have changed by a small amount. However I will check them all first tonight to ensure that nothing unexpected is happening.
Thanks 
D

**Comment by domokane** [comment]
We now have unit test cases. This is closed.

**Comment by epogrebnyak** [comment]
Glad there is progress, sorry have not been following up

сб, 6 нояб. 2021 г., 12:42 domokane ***@***.***>:

**Comment by domokane** [comment]
OK. No problems.
Regards
D
