### ISSUE TITLE
Expose SVI Parameters

### ISSUE THREAD

**Issue by armarion** [domokane/FinancePy#88]
Suppose I fit a volatility surface with a polynomial form like SVI. How do I expose the parameters form the calibrated surface?

Thanks
Alex

**Comment by domokane** [comment]
Just access the members of the class. For example if you use FinEquityVolSurface it has class members

_volatilityFunctionType - this is an enum which selects the choice of interpolator
_parameters - this is a vector of the volatility parameters

Best to look at the code in 

https://github.com/domokane/FinancePy/blob/master/financepy/market/volatility/FinEquityVolSurface.py

and

https://github.com/domokane/FinancePy/blob/master/financepy/models/FinModelVolatilityFns.py

to understand.

**Comment by armarion** [comment]
Figured it out, thanks!
