### ISSUE TITLE
Pep8 Compliant Code

### ISSUE THREAD

**Issue by domokane** [domokane/FinancePy#91]
I would like one or more people to review the pep8 branch of this project to ensure it is pep8 compliant and to let me know where it is not.

I would like to release this as the main branch in the next month.

**Comment by rkcah** [comment]
Hi,

I am sure that there are linters present to ensure PEP 8 compliance. I will test different files of this branch and see if there are any errors. Will let you know in case of any doubts.

Regards,
Saptarshi

**Comment by domokane** [comment]
Thanks. Please let me know.

**Comment by VFermat** [comment]
Hi @domokane,
There are automatic linters to ensure PEP 8 compliance. Do you want me to run a test on the PEP 8 branch?
