### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by domokane** [domokane/FinancePy#92]
The new pep8 compliant branch of this project urgently needs unit tests. 

There are already many tests under the golden folder.

What needs to be done is for someone to migrate tests from golden to units test format. A single test for each function would be a good start. There is already a test example that you can use as a guide.

Let me know if you need more information.

**Comment by rkcah** [comment]
Hi,

I can look into this. However, I had a few questions. 

Would you prefer to use a specific library for Unit Testing like [unittest](https://docs.python.org/3/library/unittest.html) or should I replicate it exactly like the example in tests/test_date.py to ensure readability? 

Also, are all the functions already being tested in the golden tests ? I feel I can start off with migrating the tests already in tests_golden and then include any other new functions that have to be tested.

I can write a couple of test files and then send a PR and we can discuss from there.

**Comment by domokane** [comment]
Sure. I am currently working on this branch which will become the main soon.

https://github.com/domokane/FinancePy/tree/more_pep_8/tests

There are two test files already under tests. These should run using pytest.

See discussion here

https://github.com/domokane/FinancePy/issues/74

Regards
D

**Comment by VFermat** [comment]
@domokane I ran the tests using the master branch and noticed some are failing. Is this expected?

**Comment by domokane** [comment]
What do you see failing ? There is one which keeps failing due to excess precision.

**Comment by domokane** [comment]
This is fixed now.
