### ISSUE TITLE
FinIborSingleCurve - optimize.newton results

### ISSUE THREAD

**Issue by suhasghorp** [domokane/FinancePy#95]
Hello,

In FinIborSingleCurve.py file, there is a call to scipy optimize.newton function for FRAs and Swaps in "_buildCurveUsing1DSolver" function as shown below:
dfMat = optimize.newton(_g, x0=dfMat, fprime=None,
                                        args=argtuple, tol=swaptol,
                                        maxiter=50, fprime2=None)
However, the results of the optimization are never used anywhere. Also, the dfMat variable now contains the optimization results and gets added to a numpy array which causes errors later in the code, since dfMat is not a real number now.
Was the intention to use the results of this optimize call to further refine the value of dfMat? In that case, we need to change the above call to:
dfMat = optimize.newton(_g, x0=dfMat, fprime=None,
                                        args=argtuple, tol=swaptol,
                                        maxiter=50, fprime2=None)[0]

Thanks

**Comment by domokane** [comment]
The output dfMat is used to seed the next root search. 

The internal curve object is updated within the root search,not using dfMat. See function _f.

    curve._dfs[numPoints - 1] = df
