### ISSUE TITLE
HullWhite - coupon bond call option

### ISSUE THREAD

**Issue by suhasghorp** [domokane/FinancePy#98]
Hello, I am trying to match HW coupon bond option price (TestFinModelRatesHW::test_HullWhiteBondOption) with the spreadsheet that comes with Hull book "DerivaGem.xls" bond option price for the same set of inputs. I am getting a rather large difference that I cannot explain. Can you please take a look ? Maybe I am making an obvious mistake.

DerivaGem price 2.3646
FinModelRatesHW price 3.846096

I have attached a screenshot of the spreadsheet as well as the python test code with matching inputs.

![image](https://user-images.githubusercontent.com/2924974/124995663-ae693e80-e015-11eb-9f0b-cb8bb4b741b9.png)

[modified_HWBondOptionTest.txt](https://github.com/domokane/FinancePy/files/6787535/modified_HWBondOptionTest.txt)

Thank you.

**Comment by domokane** [comment]
Hi - I have started looking at this. It works (agrees better) with Hull if you price it via the BondOption product. There is something that I am checking in Jamshidian to understand the difference. Often it comes down to whether there is payment of a coupon on the exercise date. But I need to complete my tests to be sure.

**Comment by suhasghorp** [comment]
Thank you. Hull spreadsheet adjusts the start date of the bond if the last coupon date was before today which I think is a little strange.
[HW_Analytic_BondOption.txt](https://github.com/domokane/FinancePy/files/6796166/HW_Analytic_BondOption.txt)

Please see the attached file.

**Comment by domokane** [comment]
Take a look at

https://github.com/domokane/FinancePy/blob/master/tests_golden/TestFinBondOptionHWModel.py

In Jamshidian, it was a coupon being included without the accrued subtracting it out at expiry. 

The tree-Jamshidian values now agree closely.

I have not been able to explain the small value difference of 2.55 (me) vs 2.36 (Hull). What dates/times/discount factors is he using for the bond flows ?
